## Intro to Python for Data Science #3


### Packages

Packages are a directory of Python scripts. Each script is called a module. Modules specify functions, methods, and new Python types. There are thousands of packages available on the Internet, some of them geared towards data science.

- Numpy: efficiently work with arrays
- Matplotlib: data visualization
- Scikit-learn: machine learning


To use packages, you have to install them on your system, and then specify in your script that you want to use the package.

You can also use one specific part of a package.


In [4]:
import numpy

array([1, 2, 3])

NameError: name 'array' is not defined

In [5]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [6]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

The from import version to import specific parts of the package can be useful to limit the amount of coding, but you are also losing some of the context. If you are working in a long Python script, and import your array function from numpy at the top, if your array function isn’t in the script until later in the code, a reader might get confused. In this case, a more standard import numpy would be preferred.

In [7]:
from numpy import array
array([1, 2, 3])

array([1, 2, 3])