## Intro to Python for Data Science #3


### Packages

Packages are a directory of Python scripts. Each script is called a module. Modules specify functions, methods, and new Python types. There are thousands of packages available on the Internet, some of them geared towards data science.

- Numpy: efficiently work with arrays
- Matplotlib: data visualization
- Scikit-learn: machine learning


To use packages, you have to install them on your system, and then specify in your script that you want to use the package.

You can also use one specific part of a package.


In [4]:
import numpy

array([1, 2, 3])

NameError: name 'array' is not defined

In [5]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [6]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

The from import version to import specific parts of the package can be useful to limit the amount of coding, but you are also losing some of the context. If you are working in a long Python script, and import your array function from numpy at the top, if your array function isn’t in the script until later in the code, a reader might get confused. In this case, a more standard import numpy would be preferred.

In [7]:
from numpy import array
array([1, 2, 3])

array([1, 2, 3])

In [11]:
import math

radius = r
r = 3

C = 2 * math.pi * r

A = math.pi * r**2

print('Circumference: ' + str(C))
print('Area: ' + str(A))

Circumference: 18.84955592153876
Area: 28.274333882308138


There are several ways to import packages and modules into Python. Depending on the import call, you’ll have to use different Python code. If you want to use the function inv( ), which is in the linalg subpackage of the scipy package, you want to be able to use this function

In [12]:
from scipy.linalg import inv as my_inv

my_inv([[1, 2], [3, 4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### NumPy

Numpy provides an alternative to Python lists - NumPy arrays. Numpy is great for doing vector arithmetic.

#### Arrays

Python doesn’t know how to do calculations on lists, so numpy is useful because it treats arrays like single values. The array is very similar to lists, however you can perform calculations over entire arrays.